from typing import TypedDict


class ResearchState(TypedDict):
    # Original user query
    query: str

    # Entity/topic the planner resolved the query to (added for disambiguation)
    resolved_entity: str

    # Generated by Planner
    sub_questions: list[str]

    # Generated by Researcher
    research_results: list[dict]

    # Generated by Critic
    critique: dict

    # Feedback from Critic
    feedback: str

    # Retry count
    retries: int

    # Generated by Writer
    final_report: str